version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: smartdocs-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: smartdocs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: smartdocs-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  app-base: &app-base
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - bun_modules:/usr/src/app/node_modules
      - whisper_models:/root/.cache/whisper-node
      - audio_data:/usr/src/app/data
    env_file:
      - ./apps/api/.env
    depends_on:
      - postgres
      - rabbitmq
    restart: unless-stopped

  api:
    <<: *app-base
    container_name: smartdocs-api
    command: bun run apps/api/src/shared/http/index.ts
    ports:
      - "8080:8080"

  gatekeeper:
    <<: *app-base
    container_name: smartdocs-gatekeeper
    command: bun run apps/api/src/shared/consumers/gatekeeper.consumer.ts

  transcriber:
    <<: *app-base
    container_name: smartdocs-transcriber
    command: bun run apps/api/src/shared/consumers/transcription.consumer.ts

  analyst:
    <<: *app-base
    container_name: smartdocs-analyst
    command: bun run apps/api/src/shared/consumers/analyst.consumer.ts

volumes:
  postgres_data:
  bun_modules:
  whisper_models:
  audio_data:
